CREATE TABLE USERS (ID INTEGER PRIMARY KEY, 
					FIRSTNAME VARCHAR(30) NOT NULL, 
					MIDDLENAME VARCHAR(30), 
					LASTNAME VARCHAR(30) NOT NULL, 
					AGE INTEGER NOT NULL, 
					GENDER CHAR(1), 
					PHONE NUMERIC(10), 
					ZIP VARCHAR(10));